Allow hot-loading of emojis
ParallelMC/ParallelUtils pull request #21
Opened 2022-11-30 03:47 UTC by EBro912

This pr would allow emojis to be hot-reloaded via a command. A player would need the `parallelutils.reloademojis` permission to run the command. While the resource pack would still need to be updated for these to work it would allow emojis to be swapped out a lot easier without having to restart the server.

2022-12-06 06:04 UTC, jakebacker requested changes
A few null checks need to be added

2022-12-06 06:04 UTC, jakebacker commented on modules/src/main/java/parallelmc/parallelutils/modules/parallelchat/commands/ParallelReloadEmojis.java
> +                int emojis = ParallelChat.get().emojiManager.getEmojis().size();
getEmojis is nullable. Add a null check

2022-12-06 06:04 UTC, jakebacker commented on modules/src/main/java/parallelmc/parallelutils/modules/parallelchat/emojis/EmojiManager.java
>              String id = emoteConfig.getString("id");
getString is nullable. Add a null check

2022-12-06 06:06 UTC, jakebacker commented on modules/src/main/java/parallelmc/parallelutils/modules/parallelchat/commands/ParallelReloadEmojis.java
> +            if (ParallelChat.get().emojiManager.loadEmojis()) {
This might require a bit restructuring for a good solution, so don't worry about it too much

2022-12-06 06:41 UTC, EBro912 commented on modules/src/main/java/parallelmc/parallelutils/modules/parallelchat/emojis/EmojiManager.java
>              String id = emoteConfig.getString("id");
I believe the null check for getString already exists underneath?

2022-12-06 15:27 UTC, jakebacker requested changes

2022-12-06 15:27 UTC, jakebacker commented on modules/src/main/java/parallelmc/parallelutils/modules/parallelchat/emojis/EmojiManager.java
>              String id = emoteConfig.getString("id");
It should be done before it's used in the Emoji constructor. Presumably that field should be NotNull so the check needs to happen before you even make the object

2022-12-07 00:31 UTC, jakebacker approved these changes

2022-12-07 00:31 UTC, jakebacker commented on modules/src/main/java/parallelmc/parallelutils/modules/parallelchat/emojis/EmojiManager.java
>              String id = emoteConfig.getString("id");
Nvm I can't read lol

2022-12-10 21:18 UTC, merged